             PGM
             /** AAVC01 ************************************/
             /*  PART INFORMATION M/F UPDATE */
             /* ... WORK FILE CLEAR                           */
             /* I-HASADA                     87.01.17      */
             /************************************ AAVC01 **/
             CLRPFM     FILE(GHCWP21)
             CLRPFM     FILE(GHCWP22)
             CLRPFM     FILE(GHCTP22)
             CLRPFM     FILE(GHCNP21)

             ENDPGM
