             PGM
             /** AB#C0E1 *********************************/
             /*  UPDATE AB#PPF1                          */
             /*  JW      2022.01.10                      */
             /********************************************/

             RUNQRY     QRY(WATALIB/EP50SP)

             CALL       PGM(AB#C0E1T)

             CALL       PGM(AB#C0E2T)

             ENDPGM
