             PGM
             /** ABAC02C *************************************/
             /*  TEST ABAR02C                                */
             /*  JW   2025.12.03                             */
             /************************************************/

             OVRDBF     FILE(ABAEL20) TOFILE(TFILE1/ABAEL20)

             CALL       PGM(HOBJ1/ABAR02C)

             ENDPGM
