             PGM
             /** ABCCTZ ********************/
             /*   TEST                     */
             /******************** ABCC01 **/
             DLTF       FILE(HAYAKAWA/TESTOK)
             MONMSG     MSGID(CPF3261 CPF2105)
             CRTPF      FILE(HAYAKAWA/TESTOK) RCDLEN(10) +
                          OPTION(*NOLIST) SIZE(2000 1000 2) +
                          LVLCHK(*NO) AUT(*ALL)

             ENDPGM
