             PGM
             /** ADAC70 **************************************/
             /*  DIVISON BY CUSTOMER MASTER MAINTENANCE      */
             /*  N-HYOTO  2000.09.14                         */
             /************************************** ADAC70 **/

 /* MAINTENANCE DIVISION BY CUSTOMER MASTER */
             STRDFU     OPTION(1 1) DFUPGM(HOBJ1/DADAPP80) +
                          FILE(HFILE1/ADAPP80)

 END:
             ENDPGM
