 PGM
/** AKAC39 ************************************************/
/*  QUENCHING KANBAN M/F DOWNLOAD FILE CREATE             */
/*                                                        */
/* TCHK1 12/07/06 CREATE                                  */
/************************************************ AKAC39 **/

             CLRPFM     FILE(HWFILE1/AKAWP39)

             CALL       PGM(AKAR39)

 ENDPGM
