             PGM
             /** ALBC21 ************************************/
             /* KANBAN BACKSIDE PUBLICATION,DELETE DATAAREA*/
             /*                                            */
             /* TCH 2001.09.21                             */
             /************************************ ALBC21 **/



             DLTDTAARA  DTAARA(ALBTUR)
             MONMSG     MSGID(CPF0000)


 END:        ENDPGM
