             PGM
             /******BBBC10**************************************/
             /* SALES UNIT PRICE TERM OF A CONTRACT UPDATE LIST HANDLING */
             /*           PROGRAM ID. : BBBC10                 */
             /*           CREATE DATE. : JAN.18,'91.           */
             /*           AUTHOR.        : K.NAKAMURA          */
             /*****************************************BBBC10***/
             CALL       PGM(BBBR10)
             ENDPGM
