             PGM
             /** CHKC49B *********************************************/
             /*  CHECK FORECAST (ABBPP50 VS ABBPP60)                 */
             /*  J.WATANABE 2023.08.29                               */
             /********************************************************/

             CLRPFM     FILE(HWFILE1/CHKWP49)

             CALL       PGM(HOBJ1/CHKR49B)

             ENDPGM
