             PGM
             /** CHKC60 **********************************************/
             /*  MENU AND USER ID LIST                               */
             /*  J.WATANABE 2019.08.19                               */
             /********************************************************/

             CLRPFM     FILE(*LIBL/CHKWP60)

             CALL       PGM(CHKR60)

             ENDPGM
