             PGM
             /** ECQC25  **************************************/
             /* TOOL CATEGORIES SUMMARY                       */
             /*                                               */
             /*                                               */
             /*************************************** ECQC25 **/
             OVRPRTF    FILE(QPRINT) OUTQ(QPRINTC) FORMTYPE(K6H1)
             CALL       PGM(ECQR25)
             DLTOVR *ALL

             ENDPGM
