             /**FCHC22***********************************************/
             /* ...MACHINE ABILITY M/F SURPLUS ENERGY TIME . SURPLUS ENERGY */
             /*  NUMBER CALCULATION ..*/
             /*        I-HASADA                     85.01.10        */
             /***********************************************FCHC22**/
             PGM
             CLRPFM     FILE(FCHNP26)
             CALL       PGM(FCHR22)
             ENDPGM
