             PGM
             /** GBFC56 ************************************/
             /*  CREATE QUOTATION DATA TO P/C                   */
             /*       TCH           2002.01.15             */
             /*                                            */
             /************************************ GBFC56 **/

             CLRPFM     FILE(GBFWP56)
             CALL       PGM(GBFR56)

             ENDPGM
