             PGM
             /********************************************/
             /*     UPDATE OF DIE ALLOTMENT M/F          */
             /*     GCQC31.      <CLP>                   */
             /*     MAR.29,'90.                          */
             /*     E.KAWASHIMA                          */
             /********************************************/
             RUNQRY     QRY(HOBJ1/GCQPL31) RCDSLT(*YES)

             ENDPGM
