             /**** GDGC40 ****************************************************/
             /*      INPUT UNIT PRICE INDEX                              */
             /*         GBC                             97/02/20             */
             /****************************************************************/
             PGM

             STRDFU     OPTION(1 1) DFUPGM(HOBJ1/DFU1) +
                          FILE(HFILE1/GDJPP10)

END:         ENDPGM
