/** GTEC05 ************************************************/
/*  ACZ PARTS A-PICS SCAN                                 */
/**********************************************************/
 PGM

             OVRDBF    FILE(AGDPP11) TOFILE(HFILE1/A@DPP11)
             OVRDBF    FILE(AGDPL11) TOFILE(HFILE1/A@DPL11)
             OVRDBF    FILE(AGDPL12) TOFILE(HFILE1/A@DPL12)

             CALL      PGM(GTER05)
             SIGNOFF

 ENDPGM
