         PGM
         /** MBDCT6 *****************************************/
         /* SALES DATA STATISTICS (OUTPUT TO IFS) NEW       */
         /*  W.WATANABE            2017.08.29               */
         /***************************************************/
             DCL        VAR(&TOKU ) TYPE(*CHAR) LEN(4)
             DCL        VAR(&NONY ) TYPE(*CHAR) LEN(4)
             DCL        VAR(&NKOJ ) TYPE(*CHAR) LEN(1)
             DCL        VAR(&NUKE ) TYPE(*CHAR) LEN(4)
             DCL        VAR(&YYYY ) TYPE(*CHAR) LEN(4)
             DCL        VAR(&MMMM ) TYPE(*CHAR) LEN(2)
             DCL        VAR(&SIZI ) TYPE(*CHAR) LEN(1)
             DCL        VAR(&TYPE ) TYPE(*CHAR) LEN(1)
             DCL        VAR(&STS  ) TYPE(*CHAR) LEN(1)

             CHGVAR     VAR(&TOKU ) VALUE('3411')
             CHGVAR     VAR(&NONY ) VALUE('0323')
             CHGVAR     VAR(&NKOJ ) VALUE(' ')
             CHGVAR     VAR(&NUKE ) VALUE('    ')
             CHGVAR     VAR(&YYYY ) VALUE('2018')
             CHGVAR     VAR(&MMMM ) VALUE('08')
             CHGVAR     VAR(&SIZI ) VALUE('1')
             CHGVAR     VAR(&TYPE ) VALUE('2')
             CHGVAR     VAR(&STS  ) VALUE(' ')

             CRTDUPOBJ  OBJ(MBDWP02) FROMLIB(HWFILE1) OBJTYPE(*FILE) +
                          TOLIB(QTEMP)
             MONMSG     MSGID(CPF0000)

             CLRPFM     FILE(QTEMP/MBDWP02)
             MONMSG     MSGID(CPF2103 CPF3261 CPF2105)

             CALL       PGM(MBDR02) PARM(&TOKU &NONY &NKOJ &NUKE +
                          &YYYY &MMMM &SIZI &TYPE &STS)

 #END:
             DLTOVR     FILE(*ALL)
             ENDPGM
