         PGM
         /** MBDCT8 *****************************************/
         /* SALES DATA STATISTICS                           */
         /*  W.WATANABE            2020.01.10               */
         /***************************************************/
             DCL        VAR(&TOKU ) TYPE(*CHAR) LEN(4)
             DCL        VAR(&NONY ) TYPE(*CHAR) LEN(4)
             DCL        VAR(&NKOJ ) TYPE(*CHAR) LEN(1)
             DCL        VAR(&NUKE ) TYPE(*CHAR) LEN(4)
             DCL        VAR(&YYYY ) TYPE(*CHAR) LEN(4)
             DCL        VAR(&MMMM ) TYPE(*CHAR) LEN(2)
             DCL        VAR(&SIZI ) TYPE(*CHAR) LEN(1)
             DCL        VAR(&TYPE ) TYPE(*CHAR) LEN(1)
             DCL        VAR(&STS  ) TYPE(*CHAR) LEN(1)

             CHGVAR     VAR(&TOKU ) VALUE('5149')
             CHGVAR     VAR(&NONY ) VALUE('5125')
             CHGVAR     VAR(&NKOJ ) VALUE(' ')
             CHGVAR     VAR(&NUKE ) VALUE('    ')
             CHGVAR     VAR(&YYYY ) VALUE('2017')
             CHGVAR     VAR(&MMMM ) VALUE('01')
             CHGVAR     VAR(&SIZI ) VALUE('4')
             CHGVAR     VAR(&TYPE ) VALUE('2')
             CHGVAR     VAR(&STS  ) VALUE(' ')

             CLRPFM     FILE(MBDWPT6)
             CLRPFM     FILE(MBDWPT6A)

             CALL       PGM(MBDRT9) PARM(&TOKU &NONY &NKOJ &NUKE +
                          &YYYY &MMMM &SIZI &TYPE &STS)

 #END:
             ENDPGM
