             PGM
             /** UCLC02 **********************************************/
             /*  CALL AAVC13A: DAILY SHIPPING VOLUME SUMMARY         */
             /*  USE 6 CHARACTER CL TO REGISTER THE MENU             */
             /*  J.WATANABAE  2021.06.14                             */
             /********************************************************/

             CALL       PGM(AAVC13A)

             ENDPGM
