             PGM
             /** UCLC04 **********************************************/
             /*  CALL AB#C0H3: RE-SEND INVOICE BY PO#                */
             /*  USE 6 CHARACTER CL TO REGISTER THE MENU             */
             /*  J.WATANABAE  2022.06.10                             */
             /********************************************************/

             CALL       PGM(AB#C0H3)

             ENDPGM
