             PGM
             /** VJBC75 ***************************************************/
             /*  IT EVENING JOB (RUN EVERYDAY/7DAYS AT 16:00)             */
             /*  J.WATANABE  2022.10.17                                   */
             /*************************************************************/

 /* SET UP ASN CUSTOMER TABLE                          */
             CALL       PGM(HOBJ1/AB#RHP) PARM(' ')

             ENDPGM
