             PGM
             /** VVVC22S ***********************************************/
             /**********************************************************/

 CPYF FROMFILE(HFILE1/AB#EP53S) TOFILE(HFILE1/AB#EP53) MBROPT(*ADD) +
                                                       FMTOPT(*MAP *DROP)
 CPYF FROMFILE(HFILE1/AB#EP54S) TOFILE(HFILE1/AB#EP54) MBROPT(*ADD) +
                                                       FMTOPT(*MAP *DROP)
 CPYF FROMFILE(HFILE1/AB#EP55S) TOFILE(HFILE1/AB#EP55) MBROPT(*ADD) +
                                                       FMTOPT(*MAP *DROP)
 CPYF FROMFILE(HFILE1/AB#EP56S) TOFILE(HFILE1/AB#EP56) MBROPT(*ADD) +
                                                       FMTOPT(*MAP *DROP)
 CPYF FROMFILE(HFILE1/AB#EP57S) TOFILE(HFILE1/AB#EP57) MBROPT(*ADD) +
                                                       FMTOPT(*MAP *DROP)
 CPYF FROMFILE(HFILE1/AB#EP58S) TOFILE(HFILE1/AB#EP58) MBROPT(*ADD) +
                                                       FMTOPT(*MAP *DROP)
 CPYF FROMFILE(HFILE1/AB#EP72S) TOFILE(HFILE1/AB#EP72) MBROPT(*ADD) +
                                                       FMTOPT(*MAP *DROP)

             ENDPGM
